name: Output Information
on: workflow_dispatch
jobs:
  output:
    name: Output Context Information
    runs-on: ubuntu-latest
    steps:
      - name: Output Github Context
        run: echo "${{ toJson(github) }}"
